export enum ActionTypeKeys {
  FETCH_RAMEN_INPROGRESS = 'FETCH_RAMEN_INPROGRESS',
  FETCH_RAMEN_SUCCESS = 'FETCH_RAMEN_SUCCESS',
  FETCH_RAMEN_FAIL = 'FETCH_RAMEN_FAIL',
  AUTH_USER_SET = 'AUTH_USER_SET',
  LOG_OUT = 'LOG_OUT'
}